### ISSUE TITLE
Ask for an ARM64 working docker.

### ISSUE THREAD

**Issue by Misterbabou** [GoodiesHQ/headscale-admin#11]
Hi,
I'm running my headscale server (docker) on a arm server and it's working great. I want to use headscale-admin (with docker). For now there is no ARM Build.
Is it plan to add the arm build on your official dockerhub repo ?

**Comment by GoodiesHQ** [comment]
Personally, the only device I have with ARM is an M1 Macbook air which is not my daily driver. I can absolutely look into multi-arch builds. It's not something I typically do, though, so I will have to read up on proper procedures for doing so.

A cursory look into this and it seems like docker buildx is all I really need to do:

`docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t goodieshq/headscale-admin:latest --push .`

That said, for the time being, it should be fairly easy to build the container on your target system. Fundamentally, this project results in only static files (you can find the admin.zip/.7z/.tar.gz in the assets of recent releases) that are not arch-dependent. The container just runs Caddy to serve the files.

I will get this done though. Thank you for the recommendation!

**Comment by GoodiesHQ** [comment]
Using similar commands to the above, I was able to build a `linux/arm64` container, but linux/arm/v7 hangs on `npm install`. I will start using github actions to build the container, I might have better luck with that.

**Comment by Misterbabou** [comment]
Thanks for the github action addition for the new image !
It works like a charm now !
