### ISSUE TITLE
routes?

### ISSUE THREAD

**Issue by ljubomirb** [GoodiesHQ/headscale-admin#12]
Hi, I'm testing this, and it looks great!!!!

My question is - is there a "routes" menu in plan? And also, I'm not sure if it is a feature of headscale and it can be done - can user be restricted to certain routes only?

I could be doing it wrong, but my use case is that I have setup a small linux box that servs as a local router, and I have 3 vlans on it. Tailscale is set on it, and it sends all vlans (i had to manually set them to be advertised). My goal was not to care about devices behind router, as they will get their IP from vlan from router, and thus automatically online. However, since I have several networks for different family members (and guests), I now end up have situation in which every user can see all of network.

I understand I should have maybe force each device to have tailscale, and each user to register, but router approach seemed way more proper way to do networking. 
So, is there a way to do it? Is it ACL thing?

Any way, good work!

**Comment by GoodiesHQ** [comment]
Hey there! Routes are currently already supported. It's worth noting that, via the API, you cannot create or advertise new routes. You can only enable or disable them. If you advertise routes (using the tailscale up command), you will see them listed in their respective node on the Nodes page and be able to confirm, enable, and disable them.

**Comment by GoodiesHQ** [comment]
Reopening because another user is also having issues with routes being  enabled. I'll wait for you to respond regarding your issue to determine if it is the same one.

**Comment by GoodiesHQ** [comment]
Closing this again. The route enabling/disabling issue has been addressed with 0.1.11b and I don't think this is actually related. Unfortunately, there is no way to create routes via the API. They must in fact be advertised by the node you wish them to be routed to.
