### ISSUE TITLE
Bare metal installation example

### ISSUE THREAD

**Issue by Ziomal12** [GoodiesHQ/headscale-admin#15]
Hey!
Your web-ui looks amazing and I'd love to have it for my config. I mainly run things on docker but as it happens the machine I'm using for Headscale is docker-free. Would you mind giving some easy to follow instructions/example on how to run it on bare-metal?

TIA

**Comment by GoodiesHQ** [comment]
Sure! I can speak to that. Considering this is just a static application, all you need to do is extract the `admin.zip/.tar.gz` file from the most recent release and serve it as a static directory, and that's it! There's really nothing special you need to do about it. It doesn't have an active service associated with it at this point. Just your standard deployment stuff:

- I highly recommend putting it behind a reverse proxy with SSL support
- If you host it on a different origin (domain/subdomain/port etc) than headscale, you should address CORS issues

But that's all! You can serve it with any HTTP server you like: Caddy, NginX, IIS, pthon, go, ruby, etc... just serve it statically. If you want to serve it in the root directory, then move all the files out of `admin` and put it in your root. If you want to use a different endpoint, simply rename `admin` to the endpoint of your choosing.

Don't overthink it, it's just some HTML, CSS, JS files!
