### ISSUE TITLE
Retain the API key

### ISSUE THREAD

**Issue by DindonSama** [GoodiesHQ/headscale-admin#20]
Hello everyone 
would anyone know if it's possible to retain the API key in a file as in the original project ?

**Comment by GoodiesHQ** [comment]
The API key, for security purposes, is only ever stored in your browser. It is never stored on the server with headscale-admin, and several other components are like this.

There is another project which, unlike headscale-admin, is NOT a static standalone set of HTML files, but is integrated into the docker ecosystem and allows you to utilize other forms of authentication to create a temporary API key when you authenticate. You can check it out here https://github.com/tale/headplane (fairly early in development)
