### ISSUE TITLE
[v0.1.12b-dev] - Invalid subfolder endpoints

### ISSUE THREAD

**Issue by arcoast** [GoodiesHQ/headscale-admin#24]
Using the above version go to `https://headscale.server.com/admin` and click in any of the boxes I've circled

![image](https://github.com/GoodiesHQ/headscale-admin/assets/81871508/75895e75-7cd8-444b-ab89-38c41b1960de)

and you'll get taken to, respectively:
 - https://headscale.server.com/users
  - https://headscale.server.com/nodes
  - https://headscale.server.com/routes
 
which all 404.

Clicking in the sidebar will take you to the correct endpoints:
 - https://headscale.server.com/admin/users
 - https://headscale.server.com/admin/nodes
 - https://headscale.server.com/admin/routes
 
 Not present in `v0.1.11b` as the boxes weren't "clickable"
 
 I've got Authelia providing access control on the `/admin/*` endpoint so my preference (and I think the "correct" solution would be to keep everything on `/admin`

**Comment by GoodiesHQ** [comment]
Ahhh thank you! You are absolutely correct. This is an issue of "it worked on my machine, so I pushed it" but for development, I'm not hosting it behind the /admin endpoint.

I forgot the base path. Adding this:

	import { base } from '$app/paths';

And changing:

			<CardTileContainer
				classes="border-solid border-[3px] border-l-[18px] {summary.border}"
				onclick={() => {
					goto(summary.path);
				}}
			>

to

			<CardTileContainer
				classes="border-solid border-[3px] border-l-[18px] {summary.border}"
				onclick={() => {
					goto(base + summary.path);
				}}
			>

Seems to have fixed it. Please re-pull the :dev container.

Thanks again!

**Comment by arcoast** [comment]
Confirmed as fixed.  Thanks @GoodiesHQ
