### ISSUE TITLE
Init issues

### ISSUE THREAD

**Issue by Seazer-x** [GoodiesHQ/headscale-admin#28]
![image](https://github.com/GoodiesHQ/headscale-admin/assets/62045004/9d0a432b-591e-4e16-a811-5fdbfb942c8c)
"After I created and saved the API key, there are no other options in the left menu except for the 'Settings' option. I'm running headscale-admin with Docker."

**Comment by Seazer-x** [comment]
![image](https://github.com/GoodiesHQ/headscale-admin/assets/62045004/2408c66d-a8ca-4855-9d83-22f3eb1dac13)

**Comment by Seazer-x** [comment]
My `headscale-admin` configuration is set up to map 80 to 8000 through Docker.  `headscale` is installed using a deb package and runs on port 8080. How can I add cross-origin permissions in `headscale`?  
![image](https://github.com/GoodiesHQ/headscale-admin/assets/62045004/bffb2baa-8af1-4191-9270-9446d9120b82)

**Comment by Seazer-x** [comment]
When I completed the deployment using Docker Compose, the display interface still did not change; my configuration is as follows:
headscale and headscale-admin:
![image](https://github.com/GoodiesHQ/headscale-admin/assets/62045004/b09f94c2-3648-4a63-87ad-d48c6019905d)
![image](https://github.com/GoodiesHQ/headscale-admin/assets/62045004/0e914724-6445-4ce8-932c-7c1932d2bba1)
traefik:
![image](https://github.com/GoodiesHQ/headscale-admin/assets/62045004/f919d079-d9f3-469c-a2f6-81e49d96c30d)

cloudflare:
![image](https://github.com/GoodiesHQ/headscale-admin/assets/62045004/a594c5f7-7d66-4ad3-adc3-7b00c557ad3f)
[configs.zip](https://github.com/GoodiesHQ/headscale-admin/files/15140799/configs.zip)

**Comment by GoodiesHQ** [comment]
Ah I will review the configurations tomorrow!

**Comment by Seazer-x** [comment]
> Ah I will review the configurations tomorrow!

Thank you very much！

**Comment by GoodiesHQ** [comment]
Ok nothing super obvious is wrong in the configuration. Can you send a picture of your Inspect Element > Developer Console output? I would be expecting to see some kind of helpful error output in there.

**Comment by Seazer-x** [comment]
> Ok nothing super obvious is wrong in the configuration. Can you send a picture of your Inspect Element > Developer Console output? I would be expecting to see some kind of helpful error output in there.

![image](https://github.com/GoodiesHQ/headscale-admin/assets/62045004/39d12a3c-ff5b-4a8e-aa2a-8afb58368797)

**Comment by Seazer-x** [comment]
> ![image](https://private-user-images.githubusercontent.com/62045004/326732923-39d12a3c-ff5b-4a8e-aa2a-8afb58368797.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0Njg0NDAsIm5iZiI6MTcxNDQ2ODE0MCwicGF0aCI6Ii82MjA0NTAwNC8zMjY3MzI5MjMtMzlkMTJhM2MtZmY1Yi00YThlLWFhMmEtOGFmYjU4MzY4Nzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDA5MDkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhMGEzMTlhNzU0MGQ2MGJhZWFiNWQyNDg0NzkxZGRhNzgwNTIzYWVhYWIyZTM2ZTFhMmNjNTRkZDhjMDQ0ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EsrM4IiM4CMFcLauIcEfzW8DowDhl87DB8E56yP9M40)

[headscale.log](https://github.com/GoodiesHQ/headscale-admin/files/15161033/headscale.log)
[traefik.log](https://github.com/GoodiesHQ/headscale-admin/files/15161034/traefik.log)

**Comment by GoodiesHQ** [comment]
Ok the cause of these problems is that your API is 404-ing. There's not a good reason I can see that it should be failing.

How about your headscale configuration? Even though the local container would run on HTTP and use port 8080, traefik in front of it would dictate that your server URL should be:

`server_url: https://headscale.snowflowers.xyz`

Please do not post your full headscale configuration as there could easily be some sensitive stuff in there. Make sure that matches and let me know.

When I make CURL requests to that URL on various endpoints, I should be getting a 401 Unauthorized (because I don't have an API key for your installation), but not a 404.

Expected:
```
PS C:\> curl.exe -H "Authorization: Bearer a1b2c3" https://headscale.example.com/api/v1/apikey
Unauthorized
```

Received:
```
PS C:\> curl.exe -H "Authorization: Bearer a1b2c3" https://headscale.snowflowers.xyz/api/v1/apikey
404 page not found

```

**Comment by Seazer-x** [comment]
![image](https://github.com/GoodiesHQ/headscale-admin/assets/62045004/a38b8019-2097-4a3d-915e-917b3f211de6)
this's my headscale configuration

**Comment by Seazer-x** [comment]
[configs.zip](https://github.com/GoodiesHQ/headscale-admin/files/15140799/configs.zip)

this's my all configuration

**Comment by source-code-sa** [comment]
i am experiencing this same issue. able to get a valid response from curl command?
curl -H "Authorization: Bearer jHooh8su-E" https://myhsurl/api/v1/apikey
{"apiKeys":[{"id":"1", "prefix":"h24w", "expiration":"2024-02-22T21:55:26.548410194Z", "createdAt":"2024-02-22T21:51:23.532824134Z", "lastSeen":null}, {"id":"2", "prefix":"jHA", "expiration":"2024-08-01T17:35:02.560685255Z", "createdAt":"2024-05-03T17:35:02.635877829Z", "lastSeen":null}]}

however same api key and url used on hs-admin wont go anywhere once saved.
my hs-admin is running over port 8443:80 where as my headscale server is running on 443:443. Both hs-admin and hs are using same url and subdomain, only diff is that hs-admin is using 8443:80 where as headscale is using https/443.
any pointers would be appreciated.

**Comment by juergenbarth** [comment]
Add the parameter
`traefik.http.middlewares.headscale-cors.headers.accesscontrolallowcredentials: true`
to your traefik CORS section.

**Comment by Seazer-x** [comment]
@juergenbarth Still not working
![image](https://github.com/GoodiesHQ/headscale-admin/assets/62045004/cd934029-a3af-44aa-b5f8-a1b8749d7542)
![image](https://github.com/GoodiesHQ/headscale-admin/assets/62045004/7eb13430-f24d-4a2a-9f8e-ab48857b435d)

**Comment by GoodiesHQ** [comment]
I am still seeing a 404 error. This tells me your headscale is what is not exactly set up properly. That URL should not 404 if it were working correctly. I'm guessing the container is not coming up properly?
