### ISSUE TITLE
Error adding client

### ISSUE THREAD

**Issue by Basti-Fantasti** [GoodiesHQ/headscale-admin#29]
Hi,

I just tried to setup the admin panel for my headscale server.
When I try to log in using a windows client, I'm forwarded to the http site showing the headscale registration info and the node registration in the form

mkey:db769b2097bb1a6c4561067e4b6daeb7ea0fe3670825d123e5bf3ea333d0e666

when I try to add a node and give the registration key as stated above (so mkey:xxx)
I always get this error message:

![grafik](https://github.com/GoodiesHQ/headscale-admin/assets/1663072/ed6476bc-c71a-4c89-8a4c-4453c5ed4594)

API connection basically works, I see the configured user on the server...

I'm running the Headscale 0.23 Alpha9 from docker hub

When checking the Legacy API switch in the Settings, I get the following error:

![grafik](https://github.com/GoodiesHQ/headscale-admin/assets/1663072/bc2a1e93-801b-44ab-a0c9-902faf8adb48)

I was able to manually add the node using the servers interface running the docker headscale ... command

headscale nodes register --user xxx --key mkey:db769b2097bb1a6c4561067e4b6daeb7ea0fe3670825d123e5bf3ea333d0e666

**Comment by GoodiesHQ** [comment]
Ah yes, ok I will get this fix out ASAP. I know exactly what the problem is, I just haven't released a patch for it as of yet. Thank you! It is basically due to the fact that headscale changed the prefix used when doing the registration via key import. The workaround at this time is to do exactly what you did to register via the command line or to use preauthkeys which do still work.

Thank you! I'll try and get the fix out this weekend :)

**Comment by Basti-Fantasti** [comment]
Thanks for your quick reply. Awesome that you made out the issue so fast.

Best regards
Bastian

**Comment by GoodiesHQ** [comment]
I have a patch in place that I am currently testing and will release as soon as I can! Sorry for the delay.

**Comment by GoodiesHQ** [comment]
Alright if you pull from the dev container it should be functional. Let me know if it works for you and I'll close this and push to main later.

**Comment by Basti-Fantasti** [comment]
Thanks, I'll try it asap and keep you updated.

**Comment by Basti-Fantasti** [comment]
I switched to the dev branch and tried it again, without success.

Here's the screenshot. Is there anyway to get more debug logouts which could assist you?

![grafik](https://github.com/GoodiesHQ/headscale-admin/assets/1663072/d8b9ceea-1474-44c8-b328-58b98fcd1198)

**Comment by Basti-Fantasti** [comment]
Where do I see if I'm on the dev branch?
The version tag in the headline is identical on the dev and on the latest branch **v0.1.12b**

**Comment by Basti-Fantasti** [comment]
Aha, now it says 1.13b in the dev branch.
I'll test again

**Comment by Basti-Fantasti** [comment]
Now it works! 🥳 

![grafik](https://github.com/GoodiesHQ/headscale-admin/assets/1663072/61a4e7da-1e4c-4ab0-9b58-44ba748e573e)


headscale was also updated to **Alpha10**
and on the 0.1.13b-dev branch it works. 👍

**Comment by GoodiesHQ** [comment]
Awesome! Thanks again for opening this, will have it merged soon.

**Comment by plittlefield** [comment]
+1
Which docker tag do I need for this?

**Comment by Drizztfire** [comment]
dev

**Comment by Drizztfire** [comment]
> +1 Which docker tag do I need for this?

dev

**Comment by plittlefield** [comment]
Right so when I put this in my image line, compose has an error saying it was not available…

0.1.13b-dev

**Comment by Drizztfire** [comment]
> Right so when I put this in my image line, compose has an error saying it was not available…
> 
> 0.1.13b-dev

goodieshq/headscale-admin:dev

**Comment by plittlefield** [comment]
Ah, thanks :-)

**Comment by yqs112358** [comment]
Hello, can you make a new release version to latest on Docker Hub? Thanks so much 🥰
