### ISSUE TITLE
[Feature request] Change Node Owner and nodes filter

### ISSUE THREAD

**Issue by dinkonin** [GoodiesHQ/headscale-admin#3]
Hi, awesome project I would like to propose the following features.
1. Provide a way to change the owner of a node (AFAIK the API exposes `/api/v1/machine/{machineId}/user` for that
2. Implement a basic filter in the nodes view (We have 50+ machines it's hard to find one) Ideally one would be able to sort the by owner or tag

Thanks again for your work.

**Comment by GoodiesHQ** [comment]
These are great additions! I added support for 1) in commit [2519211](https://github.com/GoodiesHQ/headscale-admin/commit/25192119f03cf72b70e8ee8030f4e16d18b461f7) and am working on the second one. Just trying to determine the best location for a search bar.

**Comment by GoodiesHQ** [comment]
Both solved in v0.1.4a :)
