### ISSUE TITLE
Misleading docker compose example 

### ISSUE THREAD

**Issue by Magi3r** [GoodiesHQ/headscale-admin#34]
The docker compose file does not work out of the box, if you just change the domain. The CORS rules are in conflict with the set domain names:
```
traefik.http.routers.headscale.rule: Host(`tailscale.example.com`)
traefik.http.middlewares.headscale-cors.headers.accesscontrolalloworiginlist: ""  # Add other origins if needed

traefik.http.routers.headscale-admin.rule: Host(`headscale.example.com`)
```
If you access the UI via headscale.example.com, you cannot access a headscale server running at tailscale.example.com from there because the CORS rule forbids it. It would be helpful to either set both to the same subdomain or to put the UI domain in the allow list by default.

**Comment by GoodiesHQ** [comment]
You're absolutely right. The solution is to 1) make them the same subdomain//origin or 2) add the headscale-admin rule origin in the list of CORS headers.

I will make this change in the next revision. Thank you!
