### ISSUE TITLE
Issue with adding NODES

### ISSUE THREAD

**Issue by HarryH1205** [GoodiesHQ/headscale-admin#35]
When I add node i have and error:
`Failed to create node: Unspecified Error: {"code":2,"message":"key hex string doesn't have expected type prefix mkey:","details":[]}`

key have "mkey:" pfefix before
![obraz_2024-07-17_150957450](https://github.com/user-attachments/assets/195cc1ce-677e-43b2-9fbd-4b65680f15b4)

**Comment by GoodiesHQ** [comment]
Hi there! This is a result of the API having changed  recently. If you use the -dev branch, it is up-to-date and this issue has been addressed in that branch. It will be merged into Main in the next release.

**Comment by HarryH1205** [comment]
Ok thanks for info, great job with this project!

**Comment by GoodiesHQ** [comment]
Thank you! I hope to have some additional changes out soon. Closing for now, feel free to reopen if you have further issues.
