### ISSUE TITLE
Nodes not showing

### ISSUE THREAD

**Issue by ygbillet** [GoodiesHQ/headscale-admin#36]
Hi,

Just install headscale (v0.23.0-beta1) and headscale-admin (dev-acl) through docker.
Create one user, register two nodes.

I cannot see any nodes in headscale-admin.

![image](https://github.com/user-attachments/assets/697fe787-db43-4975-a57e-ac9c29cc4b92)

But they exist in Headscale
![image](https://github.com/user-attachments/assets/a88d3623-2072-4cc4-863e-69b8ffbe9d2f)

**Comment by ygbillet** [comment]
I start debugging, open console and it's working. Probably some cache issue

**Comment by W3AXL** [comment]
I can confirm I'm seeing the same issue with `headscale-admin` running in a docker container, however in my case opening the dev console and/or force-refreshing the page doesn't seem to resolve it.

I can verify my node is connected via `docker exec headscale headscale nodes list`, however there's nothing listed under "nodes" in the web ui. So it's not a caching issue. My API key is also properly set up and I was able to create a user & set up the node using pre-auth.

No errors are seen in the docker logs either.

**Comment by W3AXL** [comment]
And as I post the comment, I believe I figured it out...

`Legacy API (Headscale < 0.23):` was checked in my settings. Disabling it seems to have fixed the issue. Fairly obvious in hindsight.
