### ISSUE TITLE
After upgrading headscale from 0.22.3 to 0.23.0, headscale-admin shows 500 internal errors for all menu items

### ISSUE THREAD

**Issue by europacafe** [GoodiesHQ/headscale-admin#41]
I've been using headscale-admin fine for headscale version 0.22.3 and I'm very happy with your work.
Today I've just upgraded headscale to its latest released version 0.23.0. Then I can not list any information.
![image](https://github.com/user-attachments/assets/148d5966-43f5-48d1-a215-ff13258afb1b)
![image](https://github.com/user-attachments/assets/e3597e05-40e9-4caf-9aca-5035b48aa62e)
![image](https://github.com/user-attachments/assets/2355c96e-de86-4875-984d-c9fe896581d4)

**Comment by europacafe** [comment]
ok. It is working now. I believe it is still using the browser cache. When I run in incognito mode, it works fine. I'm not sure how to clear cache just for this website.

**Comment by back-lacking** [comment]
@europacafe you can try to do a refresh using ctrl+f5. that should clear the cache for the site
