### ISSUE TITLE
What's the plan on endpoint security/auth?

### ISSUE THREAD

**Issue by moookino** [GoodiesHQ/headscale-admin#5]
What's the plan on endpoint security/auth?

I saw project with OIDC support or should we just use middleware to secure endpoint?

**Comment by GoodiesHQ** [comment]
I assume you found your answer which is that this endpoint does not ultimately need any security. It is just a static HTML scaffold application with all sensitive information being stored client-side and does not perform any operations server-side. I wouldn't deploy anything without SSL , but at the end of the day, securing access to this endpoint could not prevent a compromised key from being used.
