### ISSUE TITLE
Tooltip for the options on the deployment would be helpful

### ISSUE THREAD

**Issue by cchance27** [GoodiesHQ/headscale-admin#7]
Would be great if you added a popup tooltip for the various options on the Deployment page, as would save users the time of looking up for instance what "--reset" does.

**Comment by GoodiesHQ** [comment]
Simple and elegant. Good suggestion! I'm all for it. Look forward to adding it in the next version. All of the commands I got straight from tailscale CLI reference, so I can include additional information on each flag.

**Comment by GoodiesHQ** [comment]
Solved with v0.1.8b!
