### ISSUE TITLE
Only manually added tags are displayed

### ISSUE THREAD

**Issue by TymanWasTaken** [GoodiesHQ/headscale-admin#8]
Tags can be added to nodes either by listing them in `tagOwners` in the ACL file and then listing them in the `tailscale up` command, or by force-adding them through the headscale API/CLI. Most of my nodes use the first method, but I have one node (my phone) that had to use the second method, and in headscale-admin the only tag that shows up is the one on my phone. I assume this is because headscale-admin only checks the `forcedTags` key in the API response, rather than also including `validTags`, which is where the self-assigned tags are returned in:
![image](https://github.com/GoodiesHQ/headscale-admin/assets/32660892/679c6d3a-91b9-4b4d-abc0-db1d6cf4cbb4)

Side note: it is also likely a good idea to factor in the `invalidTags` key somewhere, maybe with a warning symbol

**Comment by GoodiesHQ** [comment]
Great catch and recommendation. Quite a big oversight on my part. Solved with v0.1.9b!
